service: skillhub-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  environment:
    JWT_SECRET: your-secret-key

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
